env:
  - stage: testing
    link: https://demo.openmrs.org/openmrs/login.htm, https://www.google.com/, http://live.techpanda.org/index.php/
    devices:
    - platformName: WEB
      is_headless: true
      wait: 30
      time_page_load: 30
      auto_download_driver: true
      driver_version: WebDriver\\chromedriver_114.exe
    - platformName: ANDROID
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main
    - platformName: IOS
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main
  - stage: non-prod
    link: https://demo.openmrs.org/openmrs/login.htm, https://www.google.com/, http://live.techpanda.org/index.php/
    devices:
    - platformName: WEB
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
    - platformName: ANDROID
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main
    - platformName: IOS
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main