env:
  - stage: QA
    link:
      OPEN_MRS: https://demo.openmrs.org/openmrs/login.htm
      GOOGLE: https://www.google.com/
      TECHPANDA: http://live.techpanda.org/index.php/
      TIKI: https://tiki.vn/
      IDIVA: https://idiva.vn/
    devices:
    - platformName: WEB
      is_headless: true
      wait: 30
      time_page_load: 30
      auto_download_driver: true
      driver_version: WebDriver\\chromedriver_114.exe
    - platformName: ANDROID
      is_headless: true
      wait: 30
      time_page_load: 31
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main
      udid: HVA222NA
#      udid: emulator-5554
    - platformName: IOS
      is_headless: false
      wait: 32
      time_page_load: 32
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: com.android.chrome
      appActivity: com.google.android.apps.chrome.Main
      udid: emulator-5554
  - stage: SIT
    link:
      OPEN_MRS: https://demo.openmrs.org/openmrs/login.htm
      GOOGLE: https://www.google.com/
      TECHPANDA: http://live.techpanda.org/index.php/
      TIKI: https://tiki.vn/
      IDIVA: https://idiva.vn/
    devices:
    - platformName: WEB
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
    - platformName: ANDROID
      is_headless: true
      wait: 30
      time_page_load: 31
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: vn.tiki.app.tikiandroid
      appActivity: vn.tiki.android.shopping.homeV3.HomeActivity
      udid: HVA222NA
    - platformName: IOS
      is_headless: false
      wait: 30
      time_page_load:
      auto_download_driver: false
      driver_version: WebDriver\\chromedriver_114.exe
      appPackage: vn.tiki.app.tikiandroid
      appActivity: vn.tiki.android.shopping.homeV3.HomeActivity
      udid: emulator-5554
