elements:
  - id: button-page
    description: button with text field
    locators:
      - device: WEB
        type: XPATH
        value: //span[text()="{text}"]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - &manage_offer_button
    id: manage_offer_button
    description: button with text field
    locators:
      - device: WEB
        type: XPATH
        value: //span[text()="Manage offer"]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: header-page
    description: button with text field
    locators:
      - device: WEB
        type: XPATH
        value: //*[contains(text(),"{text}")]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: outcome
    description: outcome field
    locators:
      - device: WEB
        type: ID
        value: AssessmentAndOutcomesSection_NewAssessmentOutcome_Outcome
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: option_picker
    description: Value criteria
    locators:
      - device: WEB
        type: XPATH
        value: //*[contains(@class, "picklistDataCell") and text()="{text}"]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: spinner
    description: spinner
    locators:
      - device: WEB
        type: XPATH
        value: (//*[@class="itemSpinner newSpinner48 dark"])[4]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: Basis_of_Admission
    description: AssessmentAndOutcomesSection_StudyLineItem_BasisOfAdmission
    locators:
      - device: WEB
        type: ID
        value: AssessmentAndOutcomesSection_NewAssessmentOutcome_Outcome
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: cbb_basic_admission
    description: AssessmentAndOutcomesSection_StudyLineItem_BasisOfAdmission
    locators:
      - device: WEB
        type: XPATH
        value: //*[@class="tbcInputContainer"]/following::button[@id="AssessmentAndOutcomesSection_StudyLineItem_BasisOfAdmission_picker"]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: option_table_basic_index_1
    description: External Organisation Code
    locators:
      - device: WEB
        type: XPATH
        value: (//td[@class="picklistDataCell picklistDescriptionColumn"])[1]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: button-page
    description: button with text field
    locators:
      - device: WEB
        type: XPATH
        value: //*[text()="{text}"]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - id: spinner_load_page
    description: spinner page load
    locators:
      - device: WEB
        type: XPATH
        value: (//*[@class="durationSpinner initialised"])
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - &search_toggle
    id: search_toggle
    description: External Organisation Code
    locators:
      - device: WEB
        type: XPATH
        value: //*[@class="searchToggle "]
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
  - &SearchButton
    id: SearchButton
    description: External Organisation Code
    locators:
      - device: WEB
        type: ID
        value: SearchButton
      - device: ANDROID
        type: XPATH
        value: //*[contains(text(), "android")]
      - device: IOS
        type: XPATH
        value: //*[contains(text(), "ios")]
actions:
  - id: wait-assess-status-for-course
    description: more action
    actionElements:
      - element: *SearchButton
        condition: ENABLED
        inputType: click
      - element: *manage_offer_button
        condition: ENABLED
        timeout: 1
