elements:
  - id: sort-product
    description: Sort product
    locators:
      - device: WEB
        type: XPATH
        value: (//*[@class="android.widget.EditText"])[1]
      - device: ANDROID
        type: XPATH
        value: //*[@resource-id="sortControl"]
