# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: project runner pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.2"]
        os: [ 'ubuntu-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
          os: iOS
          udid: ABCD-EFGH
          os_version: '>=15.0'
      - run: flutter drive
